Fix function for sorting ICMs
In some cases, the function could fail when sorting lists of dicts.
List of dicts are sorted by the `items()` of those dicts, which may
result in comparisons such as this one:

```python
("dependencies", list_of_dicts) < ("dependencies", list_of_dicts)

TypeError: '<' not supported between instances of
'collections.OrderedDict' and 'collections.OrderedDict'
```

Instead of sorting lists of dicts by `items()`, sort by `"purl"`.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>